spring.application.name=athis-user-service
server.port=8080

# ===============================
# MySQL
# ===============================
spring.datasource.url=${ATHIS_USER_DB_URL:jdbc:mysql://localhost:3306/athis_user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8}
spring.datasource.username=${ATHIS_USER_DB_USERNAME:root}
spring.datasource.password=${ATHIS_USER_DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JWT / OAuth2 Resource Server
# ===============================
security.jwt.issuer=${ATHIS_JWT_ISSUER:http://localhost:8081}
security.jwt.client-id=${ATHIS_JWT_CLIENT_ID:athis-first-party}
security.jwt.audience=${ATHIS_USER_JWT_AUDIENCE:athis-user-service}
security.jwt.jwk-set-uri=${ATHIS_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
spring.jpa.open-in-view=false

# ===============================
# JPA / Hibernate
# ===============================
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
